- hosts: all
  connection: httpapi
  tasks:

    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Get Access Policy
      cisco.fmcansible.fmc_configuration:
        operation: getAllAccessPolicy
        register_as: accesspolicy
        path_params:
          domainUUID: '{{ domain[0].uuid }}'

    - name: Find a file policy
      cisco.fmcansible.fmc_configuration:
        operation: getAllFilePolicy
        register_as: file_policies
        path_params:
          domainUUID: '{{ domain[0].uuid }}'

    # - name: Setup a syslog server
    #   cisco.fmcansible.fmc_configuration:
    #     operation: upsertSyslogServer
    #     data:
    #       name: 10.0.4.5:514
    #       useManagementInterface: True
    #       protocol: UDP
    #       host: 10.0.4.5
    #       port: "514"
    #       type: syslogserver
    #     filters:
    #       host: 10.0.4.5
    #     register_as: syslog_server

    - name: Create an access rule logging malware files
      cisco.fmcansible.fmc_configuration:
        operation: upsertAccessRule
        data:
          name: Log traffic with malware files 2
          action: ALLOW
          logEnd: True
          logBegin: False
          sendEventsToFMC : True
          filePolicy: "{{ file_policies[0] }}"
          type: AccessRule
        path_params:
          containerUUID: '{{ accesspolicy[0].id }}'
          domainUUID: '{{ domain[0].uuid }}'
          objectId: '02EBAC31-2E98-0ed3-0000-000268460035'