- hosts: vfmc
  gather_facts: False
  any_errors_fatal: true
  connection: httpapi
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Get accessPolicy
      cisco.fmcansible.fmc_configuration:
        path_params:
          domainUUID: "{{ domain[0].uuid }}"
        operation: getAllAccessPolicy
        register_as: accessPolicy
    - debug: var=accessPolicy
    - name: device onboarding
      cisco.fmcansible.fmc_configuration:
        operation: createDevice
        data:
          hostName: "172.31.80.61"
          license_caps:
            - 'BASE'
          ftdMode: 'ROUTED'
          type: Device
          regKey: "ERFVghbs567"
          performanceTier: "FTDv30"
          name: "FTD1"
          accessPolicy: "{{ accessPolicy[0] }}"
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        register_as: ftd
