- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Setup an identity policy
      cisco.fmcansible.fmc_configuration:
        operation: upsertIdentityPolicy
        data:
          name: NGFW-Default-Identity-Policy
          type: identitypolicy
        path_params:
          domainUUID: '{{ domain[0].uuid }}' 
        register_as: identity_policy

    # - name: Enable the identity policy as a part of access policy
    #   cisco.fmcansible.fmc_configuration:
    #     operation: upsertAccessPolicy
    #     data:
    #       name: NGFW-Access-Policy
    #       defaultAction:
    #         action: BLOCK
    #         logEnd: True
    #       identityPolicySetting: "{{ identity_policy }}"
    #       type: accesspolicy

    # - name: Disable the identity policy from access policy
    #   cisco.fmcansible.fmc_configuration:
    #     operation: upsertAccessPolicy
    #     data:
    #       name: NGFW-Access-Policy
    #       defaultAction:
    #         action: BLOCK
    #       identityPolicySetting: null
    #       type: accesspolicy
