- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Create Prefilter Policy
      cisco.fmcansible.fmc_configuration:
        operation: upsertPrefilterPolicy
        data:
          name: NGFW-Prefilter-Policy7
          defaultAction:
            action: BLOCK_TUNNELS
            type: PrefilterPolicyDefaultAction
          type: PrefilterPolicy
        path_params:
          domainUUID: '{{ domain[0].uuid }}'

    - name: Create Prefilter Policy
      cisco.fmcansible.fmc_configuration:
        operation: updatePrefilterPolicy
        data:
          name: NGFW-Prefilter-Policy7
          defaultAction:
            action: BLOCK_TUNNELS
            type: PrefilterPolicyDefaultAction
          type: PrefilterPolicy
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
          objectId: '{{ PrefilterPolicy_ngfw_prefilter_policy7.id }}'

    