- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Setup the first destination network for static route
      cisco.fmcansible.fmc_configuration:
        operation: upsertNetworkObject
        data:
          name: PrivateNetwork4
          value: 192.168.4.0/24
          type: networkobject
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        register_as: network_object4

    - name: Setup the second destination network for static route
      cisco.fmcansible.fmc_configuration:
        operation: upsertNetworkObject
        data:
          name: PrivateNetwork5
          value: 192.168.5.0/24
          type: networkobject
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        register_as: network_object5
    - name: Setup gateway network for static route
      cisco.fmcansible.fmc_configuration:
        operation: upsertHostObject
        data:
          name: Router2
          value: 192.168.2.1
          type: "Host"
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        register_as: router
      
    - name: Get Devices
      cisco.fmcansible.fmc_configuration:
        operation: getAllDevice
        path_params:
          domainUUID: '{{ domain[0].uuid }}' 
        register_as: device_list

    - name: Get Device Interfaces
      cisco.fmcansible.fmc_configuration:
        operation: getAllFTDPhysicalInterface
        path_params:
          containerUUID: '{{ device_list[0].id }}'
          domainUUID: '{{ domain[0].uuid }}'
        register_as: interface_list

    - name: Setup static route
      cisco.fmcansible.fmc_configuration:
        operation: upsertIPv4StaticRouteModel
        data:
          interfaceName: "{{ interface_list[1].name }}"
          selectedNetworks:
            - "{{ network_object4 }}"
            - "{{ network_object5 }}"
          gateway: "{{ router }}"
          name: "test_static_route"
          metricValue: 1
          type: IPv4StaticRoute
        path_params:
          containerUUID: '{{ device_list[0].id }}'
          domainUUID: '{{ domain[0].uuid }}'
